---
- hosts: all
  vars:
    ROOT_PW: "{{ lookup('env','ROOT_PW') }}"
    DEPLOY_PW: "{{ lookup('env','DEPLOY_PW') }}"
    SSH_PUB: "{{ lookup('env', 'SSH_PUB') }}"

    common_packages:
      - unattended-upgrades
  tasks:
    - name: Change root password
      user: name=root password="{{ ROOT_PW }}"

    - name: Add deploy user
      user: name=deploy password="{{ DEPLOY_PW }}" shell=/bin/bash

    - name: Add authorized keys for deploy user
      authorized_key: user=deploy
                      key="{{ SSH_PUB }}"

    - name: Add authorized keys for root user
      authorized_key: user=root
                      key="{{ SSH_PUB }}"

    - name: Add deploy user to sudoers
      lineinfile: dest=/etc/sudoers
                  regexp="deploy ALL"
                  line="deploy ALL=(ALL) ALL"
                  state=present

    - name: Update APT package cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade APT to the latest packages
      apt: upgrade=safe

    - name: Install required packages
      apt: state=latest pkg={{ common_packages }}

    - name: Adjust APT update intervals
      copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic mode=600

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Disallow PAM
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^UsePAM"
                  line="UsePAM no"
                  state=present
      notify: Restart ssh

    - name: Disallow Challenge Response
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^ChallengeResponseAuthentication"
                  line="ChallengeResponseAuthentication no"
                  state=present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
