---
# https://blog.veloc1ty.de/2018/08/06/pgp-trust-key-non-interactive-with-ansible/
- hosts: all
  tasks:
    - name: Create mhkr
      file:
        path: /root/mhkr
        state: directory
        mode: '0700'

    - name: Upload pgp key
      copy:
        content: "{{ lookup('url', 'https://raw.githubusercontent.com/HoffsMH/mhkr.io/master/dist/key.pub', split_lines=False) }}"
        dest: /root/mhkr/pub
        mode: 600

    - name: import pgp key
      command: "gpg --import /root/mhkr/pub"

    - name: Extract fingerprint
      shell: gpg --with-fingerprint --with-colons /root/mhkr/pub | grep fpr | cut -d ':' -f 10
      register: pgpfingerprint

    - name: Create ownertrust
      copy:
        content: "{{ pgpfingerprint.stdout }}:6:\n"
        dest: /root/mhkr/ownertrust
        mode: 600

    - name: Import ownertrust
      shell: "gpg --import-ownertrust /root/mhkr/ownertrust"
