---
  - name: Change root password
    user: name=root

  - name: Add deploy user
    user: name=deploy

  - name: Add authorized keys for deploy user
    authorized_key: user=deploy
                    key="{{ lookup('env', 'SSH_PUB') }}"

  - name: Add authorized keys for root user
    authorized_key: user=root
                    key="{{ lookup('env', 'SSH_PUB') }}"

  - name: Add deploy user to sudoers
    lineinfile: dest=/etc/sudoers
                regexp="deploy ALL"
                line="deploy ALL=(ALL) ALL"
                state=present

  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade APT to the latest packages
    apt: upgrade=safe

  - name: Install unattended-upgrades
    apt: state=latest pkg=unattended-upgrades

  - name: Adjust APT update intervals
    copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic mode=600

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: Allow PAM
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^UsePAM"
                line="UsePAM yes"
                state=present
    notify: Restart ssh

  - name: Disallow Challenge Response
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^ChallengeResponseAuthentication"
                line="ChallengeResponseAuthentication no"
                state=present
    notify: Restart ssh
