---

# https://stackoverflow.com/questions/39204455/ansible-how-to-init-git-bare-repository-and-clone-it-to-the-same-machine
- hosts: all
  vars:
    packages:
      - git
  tasks:
    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: Add git user
      user: name=git

    - name: ensure git directory is present and owned by git
      file:
        path: /srv/git/
        owner: git
        group: git
        mode: '0700'
        state: directory

    - name: Add authorized keys for git user
      authorized_key: user=git
                      key="{{ lookup('env', 'SSH_PUB') }}"

    - name: initializes pass repo only if it doesn't exist
      command: git init --bare /srv/git/pass.git
      args:
        creates: /srv/git/pass.git/HEAD
      become_user: git
