---
- name: ssh setup
  import_playbook: ../ssh/deploy.yml

- name: nginx install
  import_playbook: ../nginx/deploy.yml

- name: import my public key
  import_playbook: ../import-public-gpg-key/deploy.yml

- hosts: all
  vars:
    packages:
      - git
      - duplicity
  tasks:

    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: Copy file with owner and permissions
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/sites-enabled/mhkr.io.conf
        owner: root
        group: root
        mode: '0700'
        force: no

    - git:
        repo: 'https://github.com/HoffsMH/mhkr.io.git'
        dest: /srv/git/mhkr.io
        force: yes
        version: master

    - name: Link
      file:
        src: /srv/git/mhkr.io/dist
        dest: /srv/www
        owner: root
        group: root
        force: yes
        state: link

- name: certbot
  import_playbook: ../certbot-nginx/deploy.yml

