---
- name: ssh setup
  import_playbook: ../ssh/deploy.yml
  tags:
    - provision

- name: nginx install
  import_playbook: ../nginx/deploy.yml
  tags:
    - provision

- hosts: all
  vars:
    packages:
      - git
  tasks:
    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: copy nginx.conf over
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/sites-enabled/mhkr.io.conf
        owner: root
        group: root
        mode: '0700'
        force: no
      tags:
        - provision

    - git:
        repo: 'https://github.com/HoffsMH/mhkr.io.git'
        dest: /srv/git/mhkr.io
        force: yes
        version: master

    - name: Link
      file:
        src: /srv/git/mhkr.io/dist
        dest: /srv/www
        owner: root
        group: root
        force: yes
        state: link

    - name: restart nginx
      service:
          name: nginx
          state: restarted

- name: certbot
  import_playbook: ../certbot-nginx/deploy.yml
  tags:
    - provision

- name: git setup
  import_playbook: ../git-server/deploy.yml
  tags:
    - provision
