---
- name: ssh setup
  import_playbook: ../ssh/deploy.yml
  tags:
    - provision

- name: nginx install
  import_playbook: ../nginx/deploy.yml
  tags:
    - provision

- hosts: all
  vars:
    packages:
      - git
  tasks:
    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: copy nginx.conf over
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/sites-enabled/mhkr.io.conf
        owner: root
        group: root
        mode: '0700'
        force: no

    - git:
        repo: 'https://github.com/HoffsMH/mhkr.io.git'
        dest: /srv/git/mhkr.io
        force: yes
        version: master

    - name: Add pub as a text mime type to nginx
      replace:
        path: /etc/nginx/mime.types
        regexp: "^text"
        replace: "text/plain    txt asc text pm el c h cc hh cxx hxx f90 conf log pub;"

    - name: remove extstream
      lineinfile:
        path: /etc/nginx/mime.types
        regexp: "^application/vnd.exstream-package"
        state: absent

    - name: Link
      file:
        src: /srv/git/mhkr.io/dist
        dest: /srv/www
        owner: root
        group: root
        force: yes
        state: link

    - name: restart nginx
      service:
          name: nginx
          state: restarted

# - name: certbot
#   import_playbook: ../certbot-nginx/deploy.yml
#   tags:
#     - provision

- name: git setup
  import_playbook: ../git-server/deploy.yml
  tags:
    - provision
