---
- hosts: all
  vars:
    packages:
      - nginx
  tasks:

    - name: install packages
      apt:
        pkg: "{{ packages }}"
        state: latest
        update_cache: true

    - name: start nginx
      service:
          name: nginx
          state: started
